### ISSUE TITLE
port not available

### ISSUE THREAD

**Issue by danieleades** [yuzutech/kroki#1672]
Hi there. I'm trying to run a kroki server using docker and seeing an error exposing the port to the host. The error seems to be on the container side (it isn't affected my changing the mapping to a different host port)

i have:

```yml
version: "3"
services:

  kroki:
    image: hub.docker.seebyte.com/yuzutech/kroki
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8000:8000"
  mermaid:
    image: hub.docker.seebyte.com/yuzutech/kroki-mermaid
    ports:
      - "8002:8002"
```

and i see the following error:

> Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:8000 -> 0.0.0.0:0: listen tcp 0.0.0.0:8000: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
