### ISSUE TITLE
Error 503: Connection refused: /127.0.0.1:8005 using kroki.io

### ISSUE THREAD

**Issue by isidroas** [yuzutech/kroki#1726]
I know that the state is experimental, but maybe this is unexpected

``` example
$ cat example_circle.drawio
<mxfile host="app.diagrams.net" modified="2024-03-19T11:13:54.984Z" agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" etag="ye2kVQ-WHAUeJ5Jt8waz" version="24.0.7" type="device">
  <diagram name="Page-1" id="vslfuAEcxFfOEoTB-ut6">
    <mxGraphModel dx="2066" dy="1216" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <mxCell id="N9n0jZtnHwRh7RBWQiTI-2" value="" style="ellipse;whiteSpace=wrap;html=1;aspect=fixed;" vertex="1" parent="1">
          <mxGeometry x="320" y="440" width="80" height="80" as="geometry" />
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
$ curl https://kroki.io/diagramsnet/svg --data-binary '@-' < example_circle.drawio
Error 503: Connection refused: /127.0.0.1:8005
```

**Comment by isidroas** [comment]
On the other hand, when I use the self-hosted container, it works perfect 👍

``` yaml
# source: https://docs.kroki.io/kroki/setup/use-docker-or-podman/
version: "3"
services:
  kroki:
    image: yuzutech/kroki
    depends_on:
      - mermaid
      - bpmn
      - excalidraw
      - diagramsnet
    environment:
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
    ports:
      - "8000:8000"
  mermaid:
    image: yuzutech/kroki-mermaid
    expose:
      - "8002"
  bpmn:
    image: yuzutech/kroki-bpmn
    expose:
      - "8003"
  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"
  # my addition:
  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    expose:
      - "8005"
```

``` example
$ curl http://localhost:8000/diagramsnet/svg --data-binary '@-' < example_circle.drawio
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="82px" height="82px" viewBox="-0.5 -0.5 82 82"><defs/><g><ellipse cx="40" cy="40" rx="40" ry="40" fill="rgb(255, 255, 255)" stroke="rgb(0, 0, 0)" pointer-events="all"/></g></svg>%
```
