### ISSUE TITLE
Update wireviz version to latest

### ISSUE THREAD

**Issue by rwarren** [yuzutech/kroki#1779]
Kroki currently uses wireviz `v0.3.3` (which is not even an official version... see below).  The latest version is `v0.4.1`.  Updating would be very nice.

----

More detail...

The wireviz version currently in use is `v0.3.3`, per this line:
https://github.com/yuzutech/kroki/blob/d96fd259e2362b39707bb5a8665ec81f2aaac4df/server/ops/docker/jdk17-noble/Dockerfile#L180

Curiously, `v0.3.3` is not even an [official wireviz tag](https://github.com/wireviz/WireViz/releases)!?  Officail Wireviz versions jump from `v0.3.2` to `v0.4`, so I'm not sure how `v0.3.3` works.

The latest version of wireviz is `v0.4.1`, and it contains some significant, and long awaited, [features](https://github.com/wireviz/WireViz/releases/tag/v0.4).

_NOTE_: You can't even run basic wireviz tutorials with the `v0.3.x` version included with Kroki!  For example the syntax for [this wireviz tutorial](https://github.com/wireviz/WireViz/blob/master/tutorial/readme.md#05---ferrules-wire-bundles-custom-wire-colors) currently fails with the syntax below (also available at the kroki.io renderer [here](https://kroki.io/wireviz/svg/eNpFkE1OwzAQhfc5xUgsm1SkUKlkCYUuECCxKEVVFo47TS05nsg_Kr0WR-BkTBy3XdjyfB6_N8-SjEHpyboqA9iUww7QK6NFg9pVsJ2Us3UOq_dl2ibzdR2b_KnHCt5I4w8sHhZlhC40I99jJzQye0mazp80c6e6PvKzwJNlwu3WhsQvGrfTOXTd32-kkjTZCj5WcAPUe0VG6BFmmRSNxpjgK7lJ4bEle6qgCWankR-Nh3ir0bT-MBjcxboVob34za52Q_7v5xweX8f1uaxZSAbnqUsdORyVRUnBeFAOhnRKKs8zjT_Lc8bBiqha8HdMWUKAweM59PBOBE9FiwYtD76DPVlAIQ9Ae_AH5DrYaOSSDOeEbVnc16neXOp_C8WIHQ==)):
```
connectors:
  X1:
    pinlabels: [+12V, GND, GND, +5V]
    type: Molex 8981
    subtype: female
  F1:
    style: simple
    type: Crimp ferrule
    subtype: 0.5 mm²
    color: OG # optional color

cables:
  W1:
    category: bundle # bundle
    length: 0.3
    gauge: 0.5 mm2
    colors: [YE, BK, BK, RD] # custom colors, wirecount is implicit

connections:
  -
    - F1. # a new ferrule is auto-generated for each of the four wires
    - W1: [1-4]
    - X1: [1-4]
```

The problem is the relatively new syntax in `connections:` with `F1.`.  Drop the ` .` and it renders... but not as it should.
