### ISSUE TITLE
[kroki]: Cannot render large diagram with Error 400: Internal Server

### ISSUE THREAD

**Issue by al-cheb** [yuzutech/kroki#1827]
Config docker-compose.yaml

```
services:
  core:
    image: yuzutech/kroki
    environment:
      - KROKI_DIAGRAMSNET_HOST=diagramsnet
      - KROKI_MAX_URI_LENGTH=8192
      - KROKI_CONVERT_TIMEOUT=45s
      - KROKI_COMMAND_TIMEOUT=5s
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          cpus: 50
          memory: 512M
  diagramsnet:
    image: yuzutech/kroki-diagramsnet
    environment:
      - KROKI_MAX_BODY_SIZE=5mb
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          cpus: 50
          memory: 256M
    ports:
      - "8005:8005"
    expose:
      - "8005"
```

**How to reproduce:**

```
$ curl -v http://localhost:8000/diagramsnet/svg --data-binary '@spark.drawio.txt'

> POST /diagramsnet/svg HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.5.0
> Accept: */*
> Content-Length: 1672439
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 400 Internal Server Error
< content-type: text/plain
< content-length: 32
< 
* Connection #0 to host localhost left intact
Error 400: Internal Server
```

Logs:

```
$ docker logs a358ebe39b0f
{
  "timestamp": "1739433275254",
  "level": "WARN",
  "thread": "vert.x-eventloop-thread-1",
  "mdc": {
    "error_message": "Internal Server Error",
    "path": "/diagramsnet/svg",
    "method": "POST",
    "action": "warning",
    "error_code": "400",
    "failure_class_name": "io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$TooLongFormFieldException",
    "user_agent": "curl/8.5.0"
  },
  "logger": "io.kroki.server.error.ErrorHandler",
  "message": "Bad request",
  "context": "default"
}
```

The direct request to diagramsnet service works without issue:

```
$ curl -v http://localhost:8005/svg --data-binary '@spark.drawio.txt'
```

**What did you expect to see?**
A diagram should be rendered without errors.
