### ISSUE TITLE
Kroki container fails to draw a blockdiag diagram

### ISSUE THREAD

**Issue by alex-mashin** [yuzutech/kroki#1874]
Kroki is installed with the following fragment of `docker-compose.yml`:

```
  kroki:
    container_name: kroki
    image: yuzutech/kroki
    depends_on:
      - kroki_mermaid
      - kroki_bpmn
      - kroki_excalidraw
    environment:
      - KROKI_MERMAID_HOST=kroki_mermaid
      - KROKI_BPMN_HOST=kroki_bpmn
      - KROKI_EXCALIDRAW_HOST=kroki_excalidraw    
    restart: unless-stopped
    tmpfs:
      - /tmp
    networks:
      kroki:
    cpu_shares: 1024
    deploy:
      resources:
        limits:
          memory: 512m

(kroki_mermaid, kroki_bpmn and kroki_excalidraw are skipped)
```

kroki is called from another container with a POST request to `http://kroki:8000/blockdiag/svg`.

The body of the request is

```
blockdiag {
  Kroki -> generates -> "Block diagrams";
  Kroki -> is -> "very easy!";

  Kroki [color = "greenyellow"];
  "Block diagrams" [color = "pink"];
  "very easy!" [color = "orange"];
}
```

The responce is:

```
Error 400: Error, couldn't launch child (exec): Permission denied
 (exit code 2)
```

The container log contains:

```
{"timestamp":"1744815480814","level":"INFO","thread":"vert.x-eventloop-thread-1","mdc":{"path":"/blockdiag/svg","method":"POST","service_name":"blockdiag","action":"request_received","bytes_read":"192","user_agent":"MediaWiki/1.39.11"},"logger":"io.kroki.server.service.DiagramHandler","message":"Request received POST /blockdiag/svg","context":"default"}
{"timestamp":"1744815481073","level":"INFO","thread":"vert.x-eventloop-thread-1","mdc":{"path":"/blockdiag/svg","took":"256","method":"POST","service_name":"blockdiag","action":"convert","file_format":"svg","user_agent":"MediaWiki/1.39.11"},"logger":"io.kroki.server.service.DiagramHandler","message":"Convert took 256ms","context":"default"}
{"timestamp":"1744815481074","level":"WARN","thread":"vert.x-eventloop-thread-1","mdc":{"error_message":"Error, couldn't launch child (exec): Permission denied\n (exit code 2)","path":"/blockdiag/svg","method":"POST","action":"warning","error_code":"400","failure_class_name":"io.kroki.server.error.BadRequestException","user_agent":"MediaWiki/1.39.11"},"logger":"io.kroki.server.error.ErrorHandler","message":"Bad request","context":"default"}

```
