### ISSUE TITLE
Add support for Wire diagrams

### ISSUE THREAD

**Issue by ggrossetie** [yuzutech/kroki#282]
#### Input
```yml
connectors:
  X1:
    type: D-Sub
    subtype: female
    pinout: [DCD, RX, TX, DTR, GND, DSR, RTS, CTS, RI]
  X2:
    type: Molex KK 254
    subtype: female
    pinout: [GND, RX, TX]

cables:
  W1:
    gauge: 0.25 mm2
    length: 0.2
    color_code: DIN
    wirecount: 3
    shield: true

connections:
  -
    - X1: [5,2,1]
    - W1: [1,2,3]
    - X2: [1,3,2]
  -
    - X1: 5
    - W1: s
```
#### Output
![demo01](https://user-images.githubusercontent.com/333276/85665363-9bf6be00-b6bb-11ea-82b0-8b7c49af1a68.png)

Format:

- `mywire.gv`         GraphViz output
- `mywire.svg`        Wiring diagram as vector image
- `mywire.png`        Wiring diagram as raster image
- `mywire.bom.tsv`    BOM (bill of materials) as tab-separated text file
- `mywire.html`       HTML page with wiring diagram and BOM embedded

We can start by supporting png and svg.

#### Runtime

Python 3.7

#### Project

https://github.com/formatc1702/WireViz
