### ISSUE TITLE
The mermaid companion container errors on startup

### ISSUE THREAD

**Issue by groovytron** [yuzutech/kroki#8]
# The current behaviour

The mermaid companion seems to be broken and shows this error:

```log
Unable to start the service Error: Failed to launch chrome
```

Output of `docker-compose up`:

```log
blockdiag_1  | [2019-04-24 06:09:02 +0000] [1] [INFO] Starting gunicorn 19.9.0
blockdiag_1  | [2019-04-24 06:09:02 +0000] [1] [INFO] Listening at: http://0.0.0.0:8001 (1)
blockdiag_1  | [2019-04-24 06:09:02 +0000] [1] [INFO] Using worker: sync
blockdiag_1  | [2019-04-24 06:09:02 +0000] [7] [INFO] Booting worker with pid: 7
mermaid_1    | Unable to start the service Error: Failed to launch chrome!
mermaid_1    | 
mermaid_1    | 
mermaid_1    | TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
mermaid_1    | 
mermaid_1    |     at onClose (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:342:14)
mermaid_1    |     at Interface.helper.addEventListener (/snapshot/app/node_modules/puppeteer/lib/Launcher.js:331:50)
mermaid_1    |     at Interface.emit (events.js:187:15)
mermaid_1    |     at Interface.close (readline.js:379:8)
mermaid_1    |     at Socket.onend (readline.js:157:10)
mermaid_1    |     at Socket.emit (events.js:187:15)
mermaid_1    |     at endReadableNT (_stream_readable.js:1081:12)
mermaid_1    |     at process._tickCallback (internal/process/next_tick.js:63:19)
kroki-stack_mermaid_1 exited with code 1
kroki_1      | Apr 24, 2019 6:09:03 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
kroki_1      | INFO: Succeeded in deploying verticle
```
docker-compose.yaml:

```yaml
version: "3"
services:
  kroki:
    image: yuzutech/kroki:0.0.4
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8000:8000"
  blockdiag:
    image: yuzutech/kroki-blockdiag:0.0.4
    ports:
      - "8001:8001"
  mermaid:
    image: yuzutech/kroki-mermaid:0.0.4
    ports:
      - "8002:8002"
```

# Expected behaviour

The container should start and wait for HTTP requests.

# Way to reproduce the error

1. Put the `docker-compose.yml` in a directory
2. Run `docker-compose up` in this directory

Thanks in advance for your help.
