### ISSUE TITLE
Wrong font used when rendering Pikchr diagrams

### ISSUE THREAD

**Issue by pbendersky** [yuzutech/kroki#993]
The following Pikchr diagram renders properly in https://kroki.io:
```
box "main"
```
<img width="946" alt="Screen Shot 2021-11-24 at 5 32 46 PM" src="https://user-images.githubusercontent.com/1420884/143309267-84b53688-7b70-4fc9-b793-086cbb491e52.png">

However, the resulting URL renders with a different font (which appears to be a default serif, like Times New Roman or something):

https://kroki.io/pikchr/svg/eNpLyq9QUMpNzMxTAgATDwNT

Is there a chance the default font can be changed to match the one in Pikchr samples page? https://pikchr.org/home/doc/trunk/doc/examples.md

**Comment by Mogztter** [comment]
The `<text>` element in the `<svg>` has no font declared;

```xml
<text x="122" y="56" text-anchor="middle" fill="rgb(0,0,0)" dominant-baseline="central">pikchr.y</text>
```

The font is inherited from the HTML document.
On https://pikchr.org the font is defined on the `<body>` in https://pikchr.org/home/style.css

```css
body {
  margin: 0 auto;
  background-color: white;
  font-family: sans-serif;
  font-size: 14pt;
     -moz-text-size-adjust: none;
      -mx-text-size-adjust: none;
  -webkit-text-size-adjust: none;
}
```

When using https://kroki.io/pikchr/svg/eNpLyq9QUMpNzMxTAgATDwNT the `<svg>` is not embed in an HTML document so the font is the default/built-in browser font "Times New Roman".

Not sure if it's possible to define the font-family using Pikchr syntax so you will probably need to provide your own style if/when the SVG is embed in an HTML page.
